site_name: Monorepo Plus Plugin for MkDocs
site_description: A Plugin for adding and extending the monorepo-plugin with extra options and functionality.
site_author: Deepworks
copyright: Deepworks - 2023
repo_url: https://github.com/deepworks-net/mkdocs-monorepo-plus-plugin
extra:
    version: 1.0.0
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.indexes
        - navigation.top
        - content.code.copy
        - content.tabs
        - content.tabs.link
        - content.code.copy
        - search.suggest
        - search.highlight
        - search.share
    palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue 
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue 
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
'nav':
    - 'Home': 'index.md'
    - 'About':
        - 'Contributing': 'about/contributing.md'
        - 'Code of Conduct': 'about/code-of-conduct.md'
        - 'Release Notes': 'about/release-notes.md'
        - 'Roadmap': 'about/roadmap.md'
